# Generated by Django 5.1.5 on 2025-02-10 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_classroom_subject_teacher_alter_timetable_classroom_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('teacher', 'timeslot')},
        ),
    ]
