# Generated by Django 5.1.5 on 2025-02-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_timetable_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='weekly_hours',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
