# Generated by Django 5.1.5 on 2025-02-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_class_subject_teacher_alter_subject_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='classes',
            new_name='class_name',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
