# Generated by Django 5.1.5 on 2025-02-10 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_rename_classes_subject_class_name_alter_teacher_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='class',
            name='division',
            field=models.CharField(choices=[('A', 'Division A'), ('B', 'Division B')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='timetable',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='schedules.class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='class_name',
            field=models.ManyToManyField(related_name='schedule_subjects', to='schedules.class'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='schedules.classroom'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='schedules.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='schedules.teacher'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='schedules.timeslot'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('teacher', 'timeslot', 'day', 'classroom', 'class_assigned')},
        ),
    ]
