# Generated by Django 5.1.5 on 2025-02-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_remove_subject_class_name_subject_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='weekly_hours',
            new_name='practical_hours',
        ),
        migrations.AddField(
            model_name='subject',
            name='theory_hours',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='class',
            name='division',
            field=models.CharField(choices=[('A', 'Div A'), ('B', 'Div B')], default='A', max_length=1),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='class_name',
            field=models.ManyToManyField(to='schedules.class'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(to='schedules.teacher'),
        ),
    ]
